services:
  funda_scrapper:
    build: ./funda_scrapper
    image: funda_scrapper-image
    container_name: funda_scrapper-container
    volumes:
      - ./database:/app/database 
      - ./listings:/app/listings
    ports:
      - "8080:3000"

# This should remain unchanged
  scheduler:
    build: ./scheduler
    image: funda_scheduler-image
    container_name: funda_scheduler-container
    depends_on:
      - funda_scrapper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# volumes:
#   funda-database: