services:
  funda_scrapper:
    build: ./funda_scrapper
    image: funda_scrapper-image
    container_name: funda_scrapper-container
    volumes:
      - funda-database:/app/database 
      - funda-listings:/app/listings
    ports:
      - "8080:3000"
  pararius_scraper:
    build: ./pararius_scraper
    image: pararius_scraper_image
    container_name: pararius_scraper_container
    volumes:
      - pararius-listings:/app/listings
      - pararius-database:/app/database
    ports:
     - "8000:3030"

  huurstunt_scraper:
    build: ./huurstunt_scraper
    image: huurstunt_scraper_image
    container_name: huurstunt_scraper_container
    volumes:
      - huurstunt-listings:/app/listings
      - huurstunt-database:/app/database
    ports:
      - "8000:3060"
  kamer_scraper:
    build: ./kamer_scraper
    image: kamer_scraper_image
    container_name: kamer_scraper_container
    volumes:
      - kamer-listings:/app/listings
      - kamer-database:/app/database
    ports:
      - "8000:3090"

  kamernet_scraper:
    build: ./kamernet_scraper
    image: kamernet_scraper_image
    container_name: kamernet_scraper_container
    volumes:
      - kamernet-listings:/app/listings
      - kamernet-database:/app/database
    ports:
     - "8000:3060"
  huurwoningen_scraper:
    build: ./huurwoningen_scraper
    image: huurwoningen_scraper_image
    container_name: huurwoningen_scraper_container
    volumes:
      - huurwoningen-listings:/app/listings
      - huurwoningen-database:/app/database
    ports:
     - "8000:3080"
  directwonen_scraper:
    build: ./directwonen_scraper
    image: directwonen_scraper_image
    container_name: directwonen_scraper_container
    volumes:
      - directwonen-listings:/app/listings
      - directwonen-database:/app/database
    ports:
     - "8000:3090"


# This should remain unchanged
  scheduler:
    build: ./scheduler
    image: scheduler_image
    container_name: scheduler_container
    depends_on:
      - funda_scrapper
      - pararius_scraper
      - kamernet_scraper
      - huurwoningen_scraper
      - directwonen_scraper
      - huurstunt_scraper

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  funda-listings:
  funda-database:
  pararius-listings:
  pararius-database:
  display-information:
  huurstunt-listings:
  huurstunt-database:
  kamer-listings:
  kamer-database:
  kamernet-listings:
  kamernet-database:
  huurwoningen-listings:
  huurwoningen-database:
  directwonen-listings:
  directwonen-database: