services:
  funda_scrapper:
    build: ./funda_scrapper
    image: funda_scrapper-image
    container_name: funda_scrapper-container
    volumes:
      - shared-listings:/app/listings
      - shared-database:/app/database
    ports:
      - "8000:3000"
  pararius_scraper:
    build: ./pararius_scraper
    image: pararius_scraper_image
    container_name: pararius_scraper_container
    volumes:
      - shared-listings:/app/listings
      - shared-database:/app/database
    ports:
     - "8001:3010"

  huurstunt_scraper:
    build: ./huurstunt_scraper
    image: huurstunt_scraper_image
    container_name: huurstunt_scraper_container
    volumes:
      - shared-listings:/app/listings
      - shared-database:/app/database
    ports:
      - "8002:3020"
  kamer_scraper:
    build: ./kamer_scraper
    image: kamer_scraper_image
    container_name: kamer_scraper_container
    volumes:
      - shared-listings:/app/listings
      - shared-database:/app/databasee
    ports:
      - "8003:3030"

  kamernet_scraper:
    build: ./kamernet_scraper
    image: kamernet_scraper_image
    container_name: kamernet_scraper_container
    volumes:
      - shared-listings:/app/listings
      - shared-database:/app/database
    ports:
     - "8004:3040"
  huurwoningen_scraper:
    build: ./huurwoningen_scraper
    image: huurwoningen_scraper_image
    container_name: huurwoningen_scraper_container
    volumes:
      - shared-listings:/app/listings
      - shared-database:/app/database
    ports:
     - "8005:3050"
  directwonen_scraper:
    build: ./directwonen_scraper
    image: directwonen_scraper_image
    container_name: directwonen_scraper_container
    volumes:
      - shared-listings:/app/listings
      - shared-database:/app/database
    ports:
     - "8006:3060"


# This should remain unchanged
  scheduler:
    build: ./scheduler
    image: scheduler_image
    container_name: scheduler_container
    depends_on:
      - funda_scrapper
      - pararius_scraper
      - kamernet_scraper
      - huurwoningen_scraper
      - directwonen_scraper
      - huurstunt_scraper
      - kamer_scraper

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  shared-listings:
  shared-database:
