services:
  funda-scrapper:
    build: ./funda-scrapper
    image: funda-scrapper-image
    container_name: funda-scrapper-container
    volumes:
      - ./database:/app/database 
      - ./listings:/app/listings
    ports:
      - "8080:3000"

# This should remain unchanged
  scheduler:
    build: ./scheduler
    image: scheduler-image
    depends_on:
      - funda-scrapper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# volumes:
#   funda-database: